name: CI

on:
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash

env:
  RUSTC_WRAPPER: sccache
  SCCACHE_GHA_ENABLED: "true"

jobs:
  check:
    name: Build & Test
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache LLVM
        id: cache-llvm
        uses: actions/cache@v5
        with:
          path: C:/LLVM
          key: llvm-17-windows

      - name: Install LLVM
        if: steps.cache-llvm.outputs.cache-hit != 'true'
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "17"
          directory: "C:/LLVM"

      - name: Set LIBCLANG_PATH
        run: echo "LIBCLANG_PATH=C:/LLVM/bin" >> $GITHUB_ENV

      - name: Sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build app
        run: cargo build

      - name: Test
        run: cargo test
